---
- name: Update apt cache.
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 300

- name: Install Required Packages.
  become: yes
  apt:
    state: present
    name: "{{ packages_to_install }}"

- name: Ensure user_bin_dir="{{ user_bin_dir }}" exists.
  file:
    path: "{{ user_bin_dir }}"
    state: directory

- name: Deploy .bash_profile file.
  template:
    src: ./templates/.bash_profile.j2
    dest: ~/.bash_profile
