---
- name: Update apt cache.
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 300

- name: Install Required Packages.
  become: yes
  apt:
    state: present
    name: "{{ packages_to_install }}"

- name: Ensure user_bin_dir="{{ user_bin_dir }}" exists.
  file:
    path: "{{ user_bin_dir }}"
    state: directory

- name: Create symlinks to "{{ user_bin_dir }}"
  file:
    path: "{{ user_bin_dir }}"
    state: directory
  loop: "{{ user_bin_symlinks }}"

- name: Adjust shell config "{{ shell_user_config }}".
  ansible.builtin.lineinfile:
    path: "{{ shell_user_config }}"
    regexp: '{{ item.regexp }}'
    line: "{{ item.line }}"
  loop: "{{ shell_user_config_lines }}"
