---
- name: Install golang from an official .zip-archive.
  unarchive:
    src: "https://golang.org/dl/go{{ golang_version }}.linux-amd64.tar.gz"
    dest: "{{ user_bin_dir}}"
    remote_src: yes
    creates: "{{ user_bin_dir }}/go/bin/go"

- name: Ensure Golang directories exist.
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ golang_gopath_bin_dir }}"
    - "{{ golang_gopath_src_dir }}"

- name: Install golangci-lint linter to "{{ golang_gopath_bin_dir }}/golangci-lint".
  shell:
    cmd: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b {{ golang_gopath_bin_dir }} v{{ golang_golangci_lint_version }}
  args:
    creates: "{{ golang_gopath_bin_dir }}/golangci-lint"

- name: Add Go vars to shell config "{{ shell_user_config }}".
  ansible.builtin.lineinfile:
    path: "{{ shell_user_config }}"
    regexp: '{{ item.regexp }}'
    line: "{{ item.line }}"
  loop: "{{ golang_shell_user_config_lines }}"
