---
# https://habr.com/ru/post/516004/

- name: Update apt cache.
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 300

- name: Install zsh package.
  become: yes
  apt:
    state: present
    name: "zsh"

- name: Install Oh My Zsh.
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ user_home_dir }}/.oh-my-zsh"

- name: Change the shell of user "{{ ansible_user_id }}" to zsh.
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Clone zsh-autosuggestions repository.
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ zsh_autosuggestions_clone_dir }}"
    version: "{{ zsh_autosuggestions_version }}"

- name: zsh shell config "{{ shell_user_config }}".
  ansible.builtin.lineinfile:
    path: "{{ shell_user_config }}"
    regexp: '{{ item.regexp }}'
    line: "{{ item.line }}"
  loop: "{{ zsh_shell_user_config_lines }}"
