---
packages_to_install:
  - apt-transport-https
  - bat
  - build-essential
  - ca-certificates
  - curl
  - dkms
  - dnsutils
  - exa
  - git
  - jq
  - man
  - man-db
  - nfs-common
  - python3
  - python3-pip
  - python3-venv
  - rsync
  - ssh-client
  - sshpass
  - telnet
  - tree
  - unzip
  - vim
  - wget

user_home_dir: "~"
# user_home_dir: "{{ lookup('env','HOME') }}"
user_bin_dir: ~/.local/bin
user_bin_symlinks:
  - src: /usr/bin/batcat
    dest: "{{ user_bin_dir }}/bat"

terraform_version: "0.15.0"
terrascan_version: "1.5.0"

golang_version: "1.16.3"
golang_gopath_dir: "{{ user_home_dir }}/go"
golang_gopath_bin_dir: "{{ golang_gopath_dir }}/bin"
golang_gopath_src_dir: "{{ golang_gopath_dir }}/src"
golang_golangci_lint_version: "1.39.0"
golang_shell_user_config_lines:
  - regexp: '^export PATH=\$PATH:{{ user_bin_dir }}/go/bin'
    line: "export PATH=$PATH:{{ user_bin_dir }}/go/bin"
  - regexp: '^export GOPATH={{ golang_gopath_dir }}'
    line: "export GOPATH={{ golang_gopath_dir }}"
  - regexp: '^export PATH=\$PATH:{{ golang_gopath_bin_dir }}'
    line: "export PATH=$PATH:{{ golang_gopath_bin_dir }}"


java_jdk_package: openjdk-11-jdk

shell_user_config: "{{ '~/.zshrc' if shell_choice == 'zsh' else '~/.bashrc' }}"
shell_user_config_lines:
  - regexp: '^export PATH=\$PATH:{{ user_bin_dir }}$'
    line: "export PATH=$PATH:{{ user_bin_dir }}"
  - regexp: "^alias ls='exa'$"
    line: "alias ls='exa'"
  - regexp: "^alias gchma='git checkout main; git pull'$"
    line: "alias gchma='git checkout main; git pull'"

zsh_shell_user_config_lines:
  - regexp: '^source {{ zsh_autosuggestions_clone_dir }}/zsh-autosuggestions.zsh$'
    line: "source {{ zsh_autosuggestions_clone_dir }}/zsh-autosuggestions.zsh"
zsh_autosuggestions_version: v0.7.0
zsh_autosuggestions_clone_dir: "{{ user_home_dir }}/.zsh/zsh-autosuggestions"
# TODO: append for no GUI cases.
# GPG key prompt on Git commits.
# export GPG_TTY=$(tty)