---
# Ansible role and collections requiremetns file.
# For installation from https://galaxy.ansible.com/

roles:
  - name: geerlingguy.docker
    version: 3.1.2
    source: https://galaxy.ansible.com

collections:
  - name: community.docker
    version: 1.5.0
    source: https://galaxy.ansible.com
