---
- name: Install Terraform from an official .zip-archive.
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "{{ user_bin_dir}}"
    remote_src: yes
    creates: "{{ user_bin_dir }}/terraform"
  tags: terraform

