---
- name: Update apt cache.
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 300

- name: Install Required Packages.
  become: yes
  apt:
    state: present
    name: "{{ packages_to_install }}"

- name: Ensure user_bin_dir="{{ user_bin_dir }}" exists.
  file:
    path: "{{ user_bin_dir }}"
    state: directory
  tags:
    - terraform

- name: Deploy .bash_profile file.
  template:
    src: ./templates/.bash_profile.j2
    dest: ~/.bash_profile
  tags:
    - terraform

- name: Install Terraform from an official .zip-archive.
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "{{ user_bin_dir}}"
    remote_src: yes
    creates: "{{ user_bin_dir }}/terraform"
  tags: terraform
