---
- name: Install Terraform from an official .zip-archive.
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "{{ user_bin_dir}}"
    remote_src: yes
    creates: "{{ user_bin_dir }}/terraform"

- name: Install terrascan from GitHub release page.
  unarchive:
    src: "https://github.com/accurics/terrascan/releases/download/v{{ terrascan_version }}/terrascan_{{ terrascan_version }}_Linux_x86_64.tar.gz"
    dest: "{{ user_bin_dir}}"
    remote_src: yes
    creates: "{{ user_bin_dir }}/terrascan"
